### ISSUE TITLE
torch in action book is published?

### ISSUE THREAD

**Issue by rsarxiv** [nicholas-leonard/torch-in-action#1]
I am very interested in Torch, and the code is so great! But the book torch in action is published now? Where can I buy it? Thanks.

**Comment by nicholas-leonard** [comment]
@rsarxiv Hi. Author here. I am working on chapter 4 right now. Previous chapters should be published in MEAPs format by Manning, the publisher, in October, worst case: November 2016. 

I can't wait to read it. For now, too busy writing the next and reviewing the previous chapters.

**Comment by rsarxiv** [comment]
Thanks for your reply. I also can't wait to read it. Good luck!

**Comment by jnhwkim** [comment]
@nicholas-leonard awesome! If you need a (general) reviewer, I volunteer. I used to read In-Action series from Manning.
